<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Code Jam, Web Development, HTML5, CSS3, JavaScript, PHP, JQuery, Bootstrap 4">
    <title>Code Jam</title>

    <script src="https://kit.fontawesome.com/9254bb70f7.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">

    <link rel="shortcut icon" href="assets/img/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="w-100 mb-4">
      <nav class="navbar navbar-expand-lg container-fluid px-4">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <img src="assets/img/logo.png" alt="">
        </button>

        <div class="sm-hide order-lg-1">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                <a class="nav-link nav-scroll" href="/Code%20Jam/"
                    >Home</span></a
                >
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-scroll" href="/Code%20Jam/#courses">Courses</a>
                </li>
                <li class="nav-item">
                <a class="nav-link nav-scroll" href="/Code%20Jam/#about">About</a>
                </li>
                <li class="nav-item">
                <a class="nav-link nav-scroll" href="/Code%20Jam/#contact">Contact</a>
                </li>
            </ul>
        </div>

        <form class="form-inline my-2 my-lg-0 order-lg-last ml-lg-5">
          <div class="d-flex">
            <input
              class="form-control mr-sm-2 pl-3"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button type="submit" class="form-control search">
              <span></span>
            </button>
          </div>
        </form>

        <div class="collapse navbar-collapse px-4 scroll" id="navbarSupportedContent">
            <a href="/Code%20Jam/" class="d-flex align-items-center"><img src="assets/img/logo.png" alt="Code Jam Logo" class="logo"><span class="logo-name ml-2">Code Jam</span></a>
            <ul class="navbar-nav mr-auto lg-hide">
                    <li class="nav-item active">
                      <a class="nav-link" href="#"
                          >Home</span></a
                      > 
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Courses</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
        </div>

      </nav>
    </header>

    <!-- Body of the page -->
    <main class="row container m-auto py-5 course-card">
        <div class="card col-sm-3 card-tit p-0">
            <img src="assets/img/html.png" class="card-img-top img-fluid" alt="html course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>HTML Crash Course</u></h5>
                <p class="card-text">This bundle comes with a basic and solid intro for <i><u>HTML</u></i> along with a package of examples and exercices.</p>
            </div>
        </div>

        <div class="card col-sm-3 card-tit p-0 offset-sm-1">
            <img src="assets/img/css.png" class="card-img-top img-fluid" alt="css course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>CSS Crash Course</u></h5>
                <p class="card-text">This bundle comes with a basic and solid intro for <i><u>CSS</u></i> along with a package of examples and exercices.</p>
            </div>
        </div>

        <div class="card col-sm-3 card-tit p-0 offset-sm-1">
            <img src="assets/img/js.png" class="card-img-top img-fluid" alt="js course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>JS Crash Course</u></h5>
                <p class="card-text">This bundle comes with a basic and solid intro for <i><u>JS</u></i> along with a package of examples and exercices.</p>
            </div>
        </div>

        <div class="card col-sm-3 card-tit p-0 mt-4">
            <img src="assets/img/php.png" class="card-img-top img-fluid" alt="php course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>PHP Crash Course</u></h5>
                <p class="card-text">This bundle comes with a basic and solid intro for <i><u>PHP</u></i> along with a package of examples and exercices.</p>
            </div>
        </div>

        <div class="card col-sm-3 card-tit p-0 offset-sm-1 mt-4">
            <img src="assets/img/jquery.png" class="card-img-top img-fluid" alt="jquery course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>JQuery Crash Course</u></h5>
                <p class="card-text">Get Familiar with the basics of JQuery library. <blockquote><u>Code Less & Do More !</u></blockquote</p>
            </div>
        </div>

         <div class="card col-sm-3 card-tit p-0 offset-sm-1 mt-4">
            <img src="assets/img/json.png" class="card-img-top img-fluid" alt="json course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>JSON Crash Course</u></h5>
                <p class="card-text">This bundle comes with a basic and solid intro for <i><u>JSON</u></i> along with a package of examples and exercices.</p>
            </div>
        </div>  

        <div class="card col-sm-3 card-tit p-0 mt-4">
            <img src="assets/img/python.png" class="card-img-top img-fluid" alt="python course">
            <div class="card-body p-4">
                <h5 class="card-title"><u>Python Crash Course</u></h5>
                <p class="card-text">This bundle comes with a basic and solid intro for <i>Python</i> along with a package of examples and exercices.</p>
            </div>
        </div>
    </main>
    
    <!-- Pied de page commun de l'application -->
    
<footer class="container-fluid d-flex p-5">
    <div class="d-flex flex-column col-sm-2">
        <a href="index.php" class="d-flex align-items-center"><img src="assets/img/logo.png" alt="Code Jam Logo" class="logo"><span class="logo-name ml-2">Code Jam</span></a>
        <small>&copy; Code Jam 2020</small>
    </div>

    <div class="d-flex flex-column col-sm-2 offset-sm-3">
        <a href="#" class="text-secondary"><small>Courses</small></a>
        <a class="text-secondary my-2" href="#"><small>About</small></a>
        <a href="#" class="text-secondary"><small>Contact</small></a>
    </div>

    <div class="d-flex flex-column col-sm-2">
        <a href="#" class="text-secondary"><small>Courses</small></a>
        <a class="text-secondary my-2" href="#"><small>About</small></a>
        <a href="#" class="text-secondary"><small>Contact</small></a>
    </div>

    <div class="d-flex flex-column col-sm-2">
        <a href="#" class="text-secondary"><small>Courses</small></a>
        <a class="text-secondary my-2" href="#"><small>About</small></a>
        <a href="#" class="text-secondary"><small>Contact</small></a>
    </div>

    <a href="#"><img src="assets/img/up.png" alt="UP link" class="up"></a>

</footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="js/functions.js"></script>
    <script src="js/main.js"></script>
</body>
</html>