<section class="bg-img box" title="Home">
    <div class="middle">
        <h1>Welcome to Code Jam !</h1>
        <h2>Learn programming, web development from scratch - all on your own time</h2>
    </div>
</section>

<section class="subs text-center rounded">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <p class="m-0">Start Now For Free</p>
        </div>
        <div class="card-body p-5">
            <form>
                <div class="form-row">
                    <div class="col-sm-9">
                        <input type="text" class="form-control sub-mail" placeholder="Email Address">
                    </div>
                    <div class="col-sm-3">
                        <input type="submit" class="btn subscribe" value="Subscribe">
                    </div>
                </div>
            </form>

            <div class="form-check text-left mt-4 d-flex align-items-center" id="courses">
                <input class="form-check-input mt-0" type="checkbox" id="inlineCheckbox" value="option1">
                <label class="form-check-label sub-label" for="inlineCheckbox">I want to hear from Code Jam about new Courses and Bundles</label>
            </div>
        </div>
    </div>
</section>

<h2 class="courses-tit text-center mt-4 mb-5 box" title="Courses">Courses</h2>

<section class="courses row w-75 m-auto">
    <div class="card col-sm-5">
        <img src="assets/img/logo-1.png" class="card-img-top html-logo" alt="HTML Course logo">
        <div class="card-body text-justify pt-0 html-para">
            <p class="card-text">Learn the basics of <strong>HTML</strong> along with the best practices recommanded by the <a href="https://www.w3.org/">W3C</a> organisation.</p>
        </div>
    </div>

    <div class="card col-sm-5 offset-sm-1">
        <img src="assets/img/logo-2.png" class="card-img-top css-logo" alt="CSS Course logo">
        <div class="card-body text-justify pt-0 html-para">
            <p class="card-text">Learn the basics of <strong>CSS</strong> along with the best practices recommanded by the <a href="https://www.w3.org/">W3C</a> organisation.</p>
        </div>
    </div>

    <div class="card col-sm-5 pt-4">
        <img src="assets/img/logo-3.png" class="card-img-top js-logo" alt="JS Course logo">
        <div class="card-body text-justify pt-0 css-para">
            <p class="card-text">Learn the basics of <strong>JS</strong> along with the best practices recommanded by the <a href="https://www.w3.org/">W3C</a> organisation.</p>
        </div>
    </div>

    <div class="card col-sm-5 offset-sm-1 pt-4">
        <img src="assets/img/logo-4.png" class="card-img-top php-logo" alt="PHP Course logo">
        <div class="card-body text-justify pt-0 php-para">
            <p class="card-text">Learn the basics of <strong>PHP</strong> along with the best practices recommanded by the <a href="https://www.w3.org/">W3C</a> organisation.</p> 
        </div>
    </div>
</section>

<section class="details py-5 px-3">
    <div class="details-header d-flex justify-content-center text-center">
        <p><span>50 +</span> <br> Courses</p>
        <p><span>100</span> <br> Exercices</p>
        <p><span>50 +</span> <br> Projects</p>
        <p><span>20 +</span> <br> Viewers Rating</p>
    </div>

    <hr>

    <div class="details-footer text-center mt-5">
        <p>Start Learning Now !</p>
        <button class="btn btn-outline-info border border-info mt-2">Explore Courses</button>
    </div>

    <div id="about" class="mt-4"></div>
</section>

<h2 class="courses-tit text-center my-5 box" title="About">About</h2>

<section class="about w-75 m-auto row">
    <div class="about-left col-sm-6 rounded d-flex align-items-center">
        <div class="d-flex text-center">
            <img src="assets/img/quote1.png" alt="opening quote" class="quote1">
            <p class="w-75 m-auto">In <strong>CODE JAM</strong> code becomes <strong><u>JAM</u></strong></p>
            <img src="assets/img/quote2.png" alt="opening quote" class="quote2">
        </div>
    </div>

    <div class="about-right col-sm-6">
        <p>In Code Jam we deliver the best content for students, we try our best to simplify the code for you so that you can take the most of it !</p>
        <p>Our strategy is based on building real projects and getting familiar with problem solving and building real application</p>
        <p>All of that cames with a package of exercices which will help you improve your level up !</p>
    </div>
</section>

<div id="premium"></div>

<section class="prenium">
    <a href="#premium" class="d-flex align-items-center"><img src="assets/img/prenium.png" alt="Code Jam Logo" class="logo"><span class="logo-name ml-2">Code Jam</span></a>
    <h4 class="text-center my-4">Go Prenium & Explore Our New Features</h4>
    <p class="text-center w-50 m-auto para">In <strong style="color: #ef8688">CODE JAM</strong> we offer a new bundle for advanced topics and expert projects that will help you build you're own career</p>

    <div class="row w-75 m-auto pt-5">
        <div class="card col-sm-5 text-center">
            <div class="card-header">
                <p class="m-0 plan1">3$ / Month</p>
            </div>
            <div class="card-body basic-body">
                <h3 class="card-title"><u>Basic</u></h3>
                <p class="card-text my-4">By Purchasing This Bundle You Will Get Access To :</p>
                <p><img src="assets/img/check.png" alt="" class="check"> <strong>10</strong> New Projects</p>
                <p><img src="assets/img/check.png" alt="" class="check"> <strong>20+</strong> exercices</p>
            </div>
            <div class="card-footer btn basic-footer">Purchase</div>
        </div>    

        <div class="card col-sm-5 text-center offset-sm-1" style="width: 18rem;">
            <div class="card-header">
                <p class="m-0 plan1">5$ / Month</p>
            </div>
            <div class="card-body premium-body">
                <h3 class="card-title"><u>Premium</u></h3>
                <p class="card-text my-4">By Purchasing This Bundle You Will Get Access To :</p>
                <p><img src="assets/img/check1.png" alt="" class="check"> <strong>20</strong> New Projects</p>
                <p><img src="assets/img/check1.png" alt="" class="check"> <strong>30+</strong> exercices</p>
            </div>
            <div class="card-footer btn premium-footer">Purchase</div>
        </div>    
    </div>
</section>

<div class="main-sepra container rounded d-flex">
    <p class="sepra m-0"><strong><u>Help Us Imporve !!</u></strong> You're Help Means A Lot :)</p>
    <button class="btn">DONATE</button>
    <div id="contact" class="mt-4"></div>
</div>

<h2 class="courses-tit text-center mt-5 mb-5 box" title="Contact">Contact</h2>

<section class="contact w-75 m-auto">
    <p class="text-center"><strong class="text-info">Got A Problem !</strong> | You can send us a message !</p>

        <form class="mt-5">
            <div class="form-row">
                <div class="form-group col-sm-4 offset-sm-1">
                    <label for="firstName">First Name</label>
                    <input type="text" class="form-control border" id="firstName" name="firstName" placeholder="firstName">
                </div>
                <div class="form-group col-sm-5 offset-sm-1">
                    <label for="lastName">Last Name</label>
                    <input type="text" class="form-control border" id="lastName" name="lastName" placeholder="lastName">
                </div>
            </div>

            <div class="form-group row mt-3">
                <div class="col-sm-10 offset-sm-1">
                    <label for="email">Email Adress</label>
                    <input type="text" class="form-control border" id="email" placeholder="example@example.com" name="email">
                </div>
            </div>

            <div class="form-group row mt-4">
                <div class="col-sm-10 offset-sm-1">
                    <label for="textarea">Message</label>
                    <textarea class="form-control border" id="textarea" rows="10" name="textarea" placeholder="Enter your message !" style="resize: none"></textarea>    
                </div>
            </div>

            <div class="col-sm-3 offset-sm-5">
                <button type="submit" class="btn btn-outline-info border border-info mt-4">Send Message</button>
            </div>
        </form>
</section>

<section class="sub py-5 container-fluid">
    <h3 class="text-light col-sm-3 offset-sm-3 mb-4">Start Learning Now !</h3>
    <form>
        <div class="form-row w-100">
            <div class="col-sm-4 offset-sm-3">
                <input type="text" class="form-control sub-mail" placeholder="Email Address">
            </div>
            <div class="col-sm-3">
                <input type="submit" class="btn subscribe" value="Subscribe">
            </div>
        </div>
    </form>
</section>
